In [8]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [9]:
import tensorflow as tf
import keras
import numpy as np

In [14]:
from tensorflow.keras.preprocessing.text import one_hot


In [15]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [118]:
## Vocalbulary size
voc_size = 1000

In [119]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[726, 402, 562, 254, 296, 193], [928, 488, 562, 693, 358, 813], [277, 836, 264, 45], [726, 645, 562, 493, 726, 185], [509, 510, 479, 562, 693, 358, 813], [922, 562, 693, 358, 982, 158]]


### Word Embedding representation

In [120]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [121]:
## Pre padding
sent_length = 10
embedded_docs = pad_sequences(onehot_repr, padding="pre",maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 726 402 562 254 296 193]
 [  0   0   0   0 928 488 562 693 358 813]
 [  0   0   0   0   0   0 277 836 264  45]
 [  0   0   0   0 726 645 562 493 726 185]
 [  0   0   0 509 510 479 562 693 358 813]
 [  0   0   0   0 922 562 693 358 982 158]]


In [122]:
### 10 feature dimentions
dim = 20

In [123]:
model = Sequential()
model.add(Embedding(voc_size,20))
model.build(input_shape=(None, sent_length))
model.compile('adam', 'mse')

In [124]:
model.summary()

Model: "sequential_23"

┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Layer (type)           ┃ Output Shape    ┃   Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ embedding_22           │ (None, 10, 20)  │    20,000 │
│ (Embedding)            │                 │           │
└────────────────────────┴─────────────────┴───────────┘

 Total params: 20,000 (78.12 KB)

 Trainable params: 20,000 (78.12 KB)

 Non-trainable params: 0 (0.00 B)

In [125]:
embedded_docs[0]

array([  0,   0,   0,   0, 726, 402, 562, 254, 296, 193])

In [126]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[-0.04058447, -0.00365896,  0.00755948, -0.01040363,  0.02733977,
        -0.03397676, -0.04711812, -0.01611352,  0.03057737, -0.04580152,
         0.00641119, -0.00088023, -0.03322577, -0.03401706, -0.03518386,
         0.03801845, -0.0403735 ,  0.01142615, -0.03957732, -0.03262031],
       [-0.04058447, -0.00365896,  0.00755948, -0.01040363,  0.02733977,
        -0.03397676, -0.04711812, -0.01611352,  0.03057737, -0.04580152,
         0.00641119, -0.00088023, -0.03322577, -0.03401706, -0.03518386,
         0.03801845, -0.0403735 ,  0.01142615, -0.03957732, -0.03262031],
       [-0.04058447, -0.00365896,  0.00755948, -0.01040363,  0.02733977,
        -0.03397676, -0.04711812, -0.01611352,  0.03057737, -0.04580152,
         0.00641119, -0.00088023, -0.03322577, -0.03401706, -0.03518386,
         0.03801845, -0.0403735 ,  0.01142615, -0.03957732, -0.03262031],
       [-0.04058447, -0.00365896,  0.00755948, -0.01040363,  0.02733977,
        -0.03397676, -0.04711812, -0.01611352,  

In [129]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[[-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  [-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  [-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  ...
  [-0.04983488  0.01097322 -0.02024589 ...  0.0066219  -0.04552169
   -0.04930016]
  [ 0.00127977  0.01891123 -0.02831963 ...  0.04070215 -0.02545743
    0.03547093]
  [ 0.02899611  0.04639241  0.02996571 ... -0.01537307  0.03495124
    0.04098858]]

 [[-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  [-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  [-0.04058447 -0.00365896  0.00755948 ...  0.01142615 -0.03957732
   -0.03262031]
  ...
  [-0.04926204 -0.02109673  0.00915877 ... -0.01281559  0.01116649
   -0.04927641]
  [ 0.02888677  0.01175028 -0.02952625 ...  0.00788702 -0.03359983
   -0.0073471 ]
  [ 0.030426   -0.0207796  -0.04518

In [131]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[-0.04058447 -0.00365896  0.00755948 -0.01040363  0.02733977 -0.03397676
  -0.04711812 -0.01611352  0.03057737 -0.04580152  0.00641119 -0.00088023
  -0.03322577 -0.03401706 -0.03518386  0.03801845 -0.0403735   0.01142615
  -0.03957732 -0.03262031]
 [-0.04058447 -0.00365896  0.00755948 -0.01040363  0.02733977 -0.03397676
  -0.04711812 -0.01611352  0.03057737 -0.04580152  0.00641119 -0.00088023
  -0.03322577 -0.03401706 -0.03518386  0.03801845 -0.0403735   0.01142615
  -0.03957732 -0.03262031]
 [-0.04058447 -0.00365896  0.00755948 -0.01040363  0.02733977 -0.03397676
  -0.04711812 -0.01611352  0.03057737 -0.04580152  0.00641119 -0.00088023
  -0.03322577 -0.03401706 -0.03518386  0.03801845 -0.0403735   0.01142615
  -0.03957732 -0.03262031]
 [-0.04058447 -0.00365896  0.00755948 -0.01040363  0.02733977 -0.03397676
  -0.04711812 -0.01611352  0.03057737 -0.04580152  0.00641119 -0.00088023
  -0.03322577 -0.03401706 -0.03518386  0.03801845 -0.0403735   0.01